apiVersion: opstreelabs.in/v1alpha1
kind: MongoDB
metadata:
  name: mongodb
spec:
  kubernetesConfig:
    image: 'quay.io/opstree/mongo:v5.0.6'
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 997
  storage:
    accessModes:
      - ReadWriteOnce
    storageSize: {{ .Values.mongodb.size }}
    storageClass: {{ .Values.mongodb.class }}
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: {{ .Values.mongodb.name }}
      key: {{ .Values.mongodb.key }}
#  clusterSize: 3